### PR TITLE
1.9 port

### PR DESCRIPTION
**Pull request by Deph0**
Hi- I've ported the mod to 1.9. However, I couldn't figure out a better way to grab the inventory textures now that there's a "off-hand" texture, so the textures gets out of order and the validation of the slot is mixed up (e.g. the boots thinks it goes into the legs slot while leg texture is shown where the head slot is).

I suggest you make a new 1.9 branch before pulling this branch, so you can keep 1.8.9

I should mention that this is a premature pr- just to let you know that it got ported and is working on 1.9 just fine- except the inventory texture and validation of the amour piece getting glitched

### CODE REVIEW

**Comment by sblectric** [comment]
Hey Deph0, I've fixed your 1.9 issues in my fork and have released some jars on there.

**Comment by Deph0** [comment]
Awesome- could you do a pull request to my fork so we can add it to this PR?

**Comment by sblectric** [comment]
Done.

**Comment by Deph0** [comment]
Thanks- This is now a complete 1.9 port of this mod. A jarfile can be found on @sblectric 's fork of mine if people are interested in testing before this gets official release.

**Comment by zlainsama** [comment]
Thanks for your support.
I have added you two into the crestis.

**Pull request closed without merging**
